/* Autogenerated file. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct SuperStructure {
  uintptr_t counter;
} SuperStructure;

uint64_t rust_function(void);

struct SuperStructure *super_structure_new(void);

void super_structure_increment(struct SuperStructure *ptr);

uintptr_t super_structure_get_counter(const struct SuperStructure *ptr);

void super_structure_free(struct SuperStructure *ptr);
